"A U College Of Engg. Visakhapatnam, Visakhapatnam",
"A U College Of Engg For Women, Visakhapatnam",
"AAR Mahaveer Engineering College, Hyderabad",
"Abhinav Hi-Tech College of Engineering and Technology, Moinabad",
"Abr College Of Engg And Technology, Kanigiri",
"Adarsh College Of Engineering, Gollaprolu",
"Adi Shankara Inst Of Technology, Gudur",
"Adikavi Nannaya University College Of Engineering, Rajahmundry",
"Aditya College Of Engineering, Madanapalle",
"Aditya College Of Engineering, Peddapuram",
"Aditya College Of Engineering And Technology, Peddapuram",
"Aditya Engineering College, Peddapuram",
"Aditya Institute Of Technology And Mgmt, Tekkali",
"Adhisankara College Of Engg. And Technology, Gudur",
"Akrg College Of Engg And Technology, Nallajerla",
"Akula Sreeramulu College Of Engineering, Tanuku",
"Amalapuram Inst Of Mgmt Sci Coll Of Engg, Mummidivaram",
"A.M.Reddy Memorial Coll. Of Engineering, Narasaraopet",
"Amrita Sai Inst. Of Science And Technology, Paritala",
"Anantha Lakshmi Inst Of Technology And Sci, Anantapuramu",
"Andhra Engineering College, Atmakur N",
"Andhra Loyola Instt Of Engg And Technology, Vijayawada",
"Anil Neerukonda Institute Of Technology And Sci, Bheemunipatnam",
"Annamacharya Inst Of Tech And Sci, Kadapa",
"Annamacharya Inst Of Technology And Sciences, Rajampet",
"Annamacharya Inst Of Technology And Sciences-2Nd Shift, Rajampet",
"Annamacharya Inst Of Technology And Sciences, Tirupathi",
"Anurag University, Hyderabad",
"Anu College Of Engg Technology-Self Finance, Guntur",
"ASK College Of Technology Management, Anakapalle",
"ASN Womens Engineering College, Tenali",
"Audisankara College Of Engg And Technology, Nellore",
"Audisankara College Of Engg For Women, Gudur",
"Aurora's Technological and Research Institute, Uppal",
"Avanthi Institute Of Engg. And Technology, Narsipatnam",
"Avanthi Inst. Of Engineering And Technology, Bhogapuram",
"AVN College of Engineering, Ibrahmipatnam",
"Baba Inst Of Tech And Sciences, Visakhapatnam",
"Bandari Srinivas Institute of Technology, Chevella",
"Bapatla Engineering College, Bapatla",
"Bapatla Womens Engg College, Bapatla",
"Benaiah Inst Of Tech And Sciences, Rajahmundry",
"Bharath College Of Engg And Technology For Women, Kadapa",
"Bharath Institute of Science and Technology, Ibrahmipatnam",
"Bhaskar Engineering College, Hyderabad",
"Bheema Inst Of Technology And Sci, Adoni",
"Bhimavaram Inst. Of Engg. And Technology, Bhimavaram",
"Bhoj Reddy Engineering College for Women, Saidabad",
"Bit Institute Of Technology, Hindupur",
"BITS-Pilani, Hyderabad, Shameerpet",
"Bonam Venkata Chalamaiah Inst. Of Tech And Sci., Amalapuram",
"Brahmaiah College Of Engineering, Nellore",
"Brindavan Inst Of Technology And Sci, Kurnool",
"BVRIT Narsapur, Narsapur",
"Bvc Engineering College, Rajahmundry",
"Bvsr Engineering College, Chimakurthy",
"B V Chalamaiah Engineering College, Odalarevu",
"CBIT Hyderabad, Hyderabad",
"Chadalawada Ramanamma Engg. College, Tirupathi",
"Chaitanya Bharathi Institute Of Technology, Pallavolu",
"Chaitanya Engineering College, Visakhapatnam",
"Chaitanya Inst. Of Sci. And Technology, Kakinada",
"Chalapathi Inst Of Engg And Technology, Guntur",
"Chalapathi Inst Of Technology, Guntur",
"Chebrolu Engineering College, Guntur",
"Chintalapudi Engineering College, Guntur",
"Chirala Engineering College, Chirala",
"Chundi Ranganayakulu Engineering College, Chilakaluripet",
"CMR College Of Engineering & Technology, Kandlakoya",
"CMR Engineering college, kandlakoya",
"CMR Institute Of Technology, Kandlakoya",
"CMR Technical Campus, Kandlakoya",
"Coastal Inst Of Technology And Management, Vizianagaram",
"College Of Engineering Br Ambedkar Univ Self Finance, Srikakulam",
"CVR College of Engineering, Hyderabad",
"Dadi Instt. Of Engineering And Technology, Anakapalle",
"D.B.S.Inst Of Technology, Kavali",
"Deccan College of Engineering and Technology, Nampally",
"Dhanekula Inst Of Engg Technology, Vijayawada",
"DMSSVH College Of Engineering, Machilipatnam",
"Dnr College Of Engg And Tech, Bhimavaram",
"Dr L Bullayya College Of Engg For Women, Visakhapatnam",
"Dr Paul Rajs Engineering College, Yetapaka",
"Dr.K.V.Subba Reddy Inst. Of Technology, Kurnool",
"Dr.K.V.Subba Reddycoll Of Engg For Women, Kurnool",
"D Venkataramana And Dr.Himasekhar Mic Coll Of Tech, Kanchikacherla",
"DVR College of Engineering and Technology, Kandi",
"Ellenki College of Engineering and Technology, Patancheru",
"Eluru College Of Engg And Technology, Eluru",
"Eswar College Of Engineering, Narasaraopet",
"G. Narayanamma Institute of Technology and Science, Shaikpet",
"Gandhi Institute of Technology and Management, Rudraram",
"Gates Institute Of Technology, Gooty",
"Geethanjali College Of Engineering And Technology, Hyderabad",
"Geethanjali College Of Engineering And Technology, Kurnool",
"Geethanjali Inst Of Science And Technology, Nellore",
"Giet College Of Engineering, Rajahmundry",
"Giet Engineering College, Rajahmundry",
"Global Coll Of Engg And Technology, Chenur",
"GMR Institute Of Technology, Rajam",
"Godavari Institute Of Engg. And Technology, Rajahmundry",
"Gokraju Ranjaraju Institute of Engineering and Technology, Nizampet",
"Gokul Group Of Institutions, Bobbili",
"Gokula Krishna College Of Engineering, Sullurpet",
"Golden Valley Integrated Campus, Madanapalle",
"Gonna Inst Of Info Technology Sciences, Visakhapatnam",
"Gouthami Inst Of Technology Mgmt For Women, Proddatur",
"GPR Engineering. College, Kurnool",
"GRIET Hyderabad, Hyderabad",
"Gudlavalleru Engineering College, Gudlavalleru",
"Guntur Engineering College, Guntur",
"Guru Nanak Institute of Technology, Ibrahmipatnam",
"Guru Nanak Institutions Technical Campus, Ibrahmipatnam",
"GV VR Institute Of Technology, Bhimavaram",
"Gayathri Vidya Parishad Coll. Of Engineering, Visakhapatnam",
"Gayathri Vidya Parishad Coll Of Engg For Women, Visakhapatnam",
"GVP College For Degree And Pg Courses, Visakhapatnam",
"GVR And S College Of Engg. And Technology, Guntur",
"Helapuri Inst Of Tech And Science, Eluru",
"Hindu College Of Engineering And Technology, Guntur",
"Holy mary institute of technology, Bogaram",
"Hyderabad Institute of Technology and Management, Hyderabad",
"IARE Hyderabad, Hyderabad",
"Ideal Institute Of Technology, Kakinada",
"IIITDM Kurnool",
"IIT Hyderabad",
"IIT Tirupati",
"Indian Institute of Technology Hyderabad",
"Institute of Aeronautical Engineering, Dundigal",
"International Institute of Information Technology, Hyderabad",
"International School Of Tech And Sci For Women, Rajahmundry",
"Islamia College of Engineering and Technology, Bandlaguda",
"Jagans College Of Engg And Technology, Nellore",
"Jagruti Institute of Engineering & Technology, Ibrahmipatnam",
"Jawaharlal Nehru Technological University, Hyderabad",
"JB Institute of Engineering and Technology, Moinabad",
"Joginpally B R Engineering College, Moinabad",
"JNTUHCEH Hyderabad, Hyderabad",
"JNTUH College of Engineering, Karimnagar, Karimnagar",
"JNTUH College of Engineering, Sultanpur, Sultanpur",
"Jntua College Of Engg. Anantapuramu, Anantapuramu",
"Jntua College Of Engineering, Kalikiri",
"Jntua College Of Engg Pulivendula, Pulivendula",
"Jntuk College Of Engg. Kakinada, Kakinada",
"Jntuk College Of Engineering Narasaraopet, Narasaraopet",
"Jntuk College Of Engineering Vizianagaram, Vizianagaram",
"St. Johns College Of Engg. And Technology, Yemmiganur",
"Kakatiya Institute of Technology and Science, Warangal",
"Kakatiya University, Warangal",
"Kakinada Institute Of Engg. And Technology, Kakinada",
"Kakinada Inst Of Engg And Technology For Women, Kakinada",
"Kakinada Institute Of Technology And Science, Divili",
"Kakinada Institute Of Technology Sciences, Ramachandrapuram",
"Kallam Haranadha Reddy Inst Of Tech, Guntur",
"Kandula Obul Reddy Memorial Coll. Of Engg., Kadapa",
"Keshav Memorial Institute of Technology, Narayanguda",
"KG Reddy Engineering College, Moinabad",
"KITSW Warangal, Warangal",
"Kkr And Ksr Inst Of Technology And Sci, Guntur",
"K.Lakshumma Memorial College Of Engg For Women, Kadapa",
"KMIT Hyderabad, Hyderabad",
"Kmm Inst Of Technology And Science, Tirupathi",
"Kommuri pratap reddy institute of technology, Ghanpur",
"Krishna Chaitanya Inst Of Technology And Sciences, Markapur",
"Krishnaveni Engg College For Women, Narasaraopet",
"Krishna University College Of Engg And Technology, Machilipatnam",
"Sri Krishnadeveraya Engineering College, Gooty",
"Sri Krishnadevaraya Univ.Coll. Of Eng.- Self Finance, Anantapuramu",
"KSRM College Of Engineering, Kadapa",
"KU College of Engineering and Technology, Warangal",
"Kuppam Engineering College, Kuppam",
"Lakireddy Balireddy College Of Engineering, Mylavaram",
"Lendi Inst Of Engg And Technology, Vizianagaram",
"Lenora College Of Engineering, Rampachodavaram",
"Lingayas Inst Of Mgmt And Technology, Vijayawada",
"Lords Institute of Engineering and Technology, Rajendra Nagar",
"Loyola Institute Of Technology And Mgmt, Sattenapally",
"Madanapalle Institute Of Technology And Sci-1St Shift, Madanapalle",
"Madanapalle Institute Of Technology And Sci-2Nd Shift, Madanapalle",
"Mahatma Gandhi Institute of Technology, Gandipet",
"Mahaveer Institute of Science and Technology, Bandlaguda",
"Maheshwara College of Engineering, Rangareddy",
"Malineni Lakshmaiah Engineering College, Singarayakonda",
"Malineni Lakshmaiah Womens Engg. College, Guntur",
"Malineni Perumallu Ednl Soc Group Of Instns, Guntur",
"Malla Reddy Engineering College, Maisammaguda",
"Malla Reddy institution of technology and science, Maisammaguda",
"Mandava Institute Of Engg And Technology, Jaggaiahpet",
"Matrusri Engineering College, Saidabad",
"Maturi Venkata Subba Rao Engineering College, Nadargul",
"Megha Institute of Engineering and Technology for Women, Ghatkesar",
"Mekapati Raja Mohan Reddy Inst Of Tech And Sci., Udayagiri",
"Methodist College of Engineering and Technology, Abids",
"MGIT Hyderabad, Hyderabad",
"Miracle Ednl Soc Group Of Instns, Bhogapuram",
"Mjr College Of Engg And Technology, Piler",
"MLR Institute of Technology, Hyderabad",
"MNR College of Engineering and Technology, Kandi",
"Mother Teresa Inst Of Engg And Tech, Palamner",
"Muffakam Jha College of Engineering and Technology, Banjara hills",
"MVGR College Of Engineering, Vizianagaram",
"MVSR Engineering College, Hyderabad",
"M.V.R.Coll Of Engineering And Technology, Paritala",
"Nadimpalli Satyanarayana Raju Institute Of Technology, Visakhapatnam",
"Nalanda Institute Of Engg. And Technology, Sattenapally",
"Nalla Malla Reddy Engineering College, Ghatkesar",
"Nalla Malla Reddy Engineering College, Kachivani Singaram",
"Narasaraopet Institute Of Technology, Narasaraopet",
"Narasaraopeta Engineering College, Narasaraopet",
"Narayana Engineering College, Gudur",
"Narayana Engineering College, Nellore",
"Narayanadri Inst Of Sci Technology, Rajampet",
"National Institute of Technology, Warangal",
"Nawab Shah Alam Khan College of Engineering and Technology, New Malakpet",
"Nbkr Institute Of Sci. And Technology, Vidyanagar",
"Newton Institute Of Engineering, Macherla",
"Nimra College Of Engg And Technology, Jupudi",
"NIT Andhra Pradesh",
"Nri Institute Of Technology, Agiripalli",
"Nri Instt Of Technology, Guntur",
"N.V.R.College Of Engg Technology, Tenali",
"Osmania University, Hyderabad",
"Pace Institute Of Technology And Sciences, Ongole",
"Paladugu Parvathi Devi College Of Engg And Tech, Vijayawada",
"PBR Visvodaya Institute Of Technology And Sci., Kavali",
"P Nagaiah Choudary And Vijay Inst Of Engg And Tech, Guntur",
"Potti Sriramulu College Of Engg And Technology, Vijayawada",
"Pragati Engineering College, Peddapuram",
"Pragati Engineering College-2Nd Shift, Peddapuram",
"Prakasam Engineering College, Kandkur",
"Prasad V Potluri Siddhartha Instt Of Technology, Vijayawada",
"Prasiddha College Of Engg Technology, Anathavaram",
"Princeton College of Engineering and Technology, Ankushapur",
"Princeton Institute of engineering and technology, Ghatkesar",
"Priyadarshini College Of Engineering, Sullurpet",
"Priyadarshini Coll Of Engg. And Technology, Nellore",
"Priyadarshini Inst Of Technology, Nellore",
"Priyadarshini Inst Of Technology, Tirupathi",
"Priyadarshini Inst. Of Technology And Sciences, Tenali",
"G.Pullaiah Coll. Of Engg. And Technology, Kurnool",
"P.V.K.K. Institute Of Technology, Anantapuramu",
"Pydah College Of Engineering, Kakinada",
"Qis College Of Engg. And Technology, Ongole",
"Qis College Of Engg. And Technology-2Nd Shift, Ongole",
"Qis Institute Of Technology, Ongole",
"Raghu Engineering College, Bheemunipatnam",
"Raghu Inst. Of Technology, Bheemunipatnam",
"Rajamahendri Inst Of Engg And Technology, Rajahmundry",
"Rajiv Gandhi Memorial College Of Engg. And Tech., Nandyal",
"Rajiv Gandhi University of Knowledge Technologies, Basar",
"Ramachandra College Of Engineering, Eluru",
"Ramireddy Subba Ramireddy Engg College, Nellore",
"Ravindra College Of Engg For Women, Kurnool",
"Rayalaseema University College Of Engg, Kurnool",
"Rise Krishna Sai Gandhi Group Of Institutions, Ongole",
"Rise Krishna Sai Prakasam Group Of Institutions, Ongole",
"R.K.College Of Engineering, Ibrahimpatnam",
"RVR And J C College Of Engineering, Guntur",
"Sai Ganapathi Engineering College, Visakhapatnam",
"Sai Rajeswari Institute Of Technology, Proddatur",
"Sai Tirumala NVR Engineering College, Narasaraopet",
"Samskruti college of Engineering and Technology, Bogaram",
"Sankethika Inst Of Technology Management, Visakhapatnam",
"Sankethika Vidya Parishad Engineering College, Visakhapatnam",
"Sanskrithi School Of Engineering, Puttaparthi",
"Santhiram Engineering College, Nandyal",
"Sarada Institute Of Sci. Technology And Mgmt, Srikakulam",
"Sasi Institute Of Technology And Engineering, Tadepalligudem",
"Satya Inst Of Technology And Mgmt, Vizianagaram",
"School Of Engg. Tech. Spmvv - Self Finance, Tirupathi",
"School of Engineering Sciences and Technology, UoH, Gachibowli",
"SCIENT Institute of Technology, Ibrahmipatnam",
"Seshachala Inst Of Technology, Puttur",
"Shadan College of Engineering & Technology, Peeram Cheruvu",
"Shadan Women's College of Engineering and Technology, Khairatabad",
"Shree Inst Of Technological Education, Renigunta",
"Shree Rama Ednl Soc Grp Of Instns, Tirupati",
"Shri Shirdi Sai Inst Of Sci And Engg, Anantapuramu",
"Shri Vishnu Engg. College For Women, Bhimavaram",
"Siddharth Institute Of Engg. And Technology, Puttur",
"Siddhartha Institute of Technology and Sciences, Ibrahmipatnam",
"Siddartha Ednl Academy Grp Of Instns, Tirupathi",
"Siddhartha Inst Of Sci And Technology, Puttur",
"Simhadri Ednl Soc Grp Of Instns, Sabbavaram",
"Sir C R R College Of Engineering, Eluru",
"Sir C.V Raman Inst Of Technology Sciences, Tadipatri",
"Sir Vishveshwaraiah Inst Of Science And Technology, Madanapalle",
"SNIST Ghatkesar, Ghatkesar",
"Sphoorthy Engineering College, Vanasthallipuram",
"Sree Rama Engineering College, Tirupathi",
"Sree Vahini Institute Of Science And Technology, Tiruvuru",
"Sree Venkateswara College Of Engg, Nellore",
"Sree Vidyanikethan Engineering College, Rangampeta",
"Sreenidhi institute of science and technology, Ghatkesar",
"Sreyas Institute Of Engineering & Technology, Bandlaguda",
"Sri Annamacharya Institute Of Technology And Science, Rajampet",
"Sri Chaitanya -Djr Coll Of Engg And Tech, Vijayawada",
"Sri Chaitanya Djr Institute Of Engineering And Technology, Vijayawada",
"Sri Datta College of Engineering, Ibrahmipatnam",
"Sri Indu College of Engineering and Technology, Ibrahmipatnam",
"SRKR Engineering College, Bhimavaram",
"SRKR Engineering College-2Nd Shift, Bhimavaram",
"SRK Inst. Of Technology, Vijayawada",
"Sri Mittapalli College Of Engineering, Guntur",
"Sri Mittapalli Inst Of Technology For Women, Guntur",
"Sri Raghavendra Inst Of Technology And Sci., Vinjamur",
"Sri Sai Institute Of Technology. And Sci.., Rayachoti",
"Sri Sarathi Institute Of Engg. And Technology, Nuzvid",
"Sri Satyanarayana Engineering College, Ongole",
"Sri Sivani College Of Engineering, Srikakulam",
"Sri Sunflower College Of Engg And Technology, Lankapalli",
"Sri Vasavi Engineering College, Tadepalligudem",
"Sri Vasavi Instt Of Engineering And Technology., Pedana",
"Sri Venkateswara Coll Of Engineering, Srikakulam",
"Sri Venkateswara Coll Of Engineering, Tirupathi",
"Sri Venkateswara College Of Engg. And Technology., Chittoor",
"Sri Venkateswara College Of Engineering, Kadapa",
"Sri Venkateswara Engg College, Tirupathi",
"Sri Venkateswara Inst Of Technology, Anantapuramu",
"Sri Venkateswara Instt. Of Science And Technology., Kadapa",
"Sri Venkatesa Perumal College Of Engg. And Tech, Puttur",
"Sridevi Women's Engineering College, Vattinagulapally",
"Srinivasa Institute Of Technology And Mang Studies, Chittoor",
"Srinivasa Inst Of Engg And Technology, Cheyyeru",
"Srinivasa Inst Of Technology Science, Kadapa",
"Srinivasa Ramanujan Inst Of Technology, Anantapuramu",
"St. Anns College Of Engg. And Technology, Chirala",
"St. Martins Engineering College, Dhulapally",
"Stanley College of Engineering and Technology for Women, Abids",
"Sumathi Reddy Institute of Technology for Women, Ananthsagar",
"SVU College Of Engg. Tirupathi, Tirupathi",
"Svr Engineering College, Nandyal",
"Swarnandhra Coll. Of Engg And Technology, Narsapuram",
"Swarnandhra Coll. Of Engg And Tech-2Nd Shift, Narsapuram",
"Swarnandhra Inst. Of Engg And Technology, Narsapuram",
"Swetha Institute Of Technology And Science, Tirupathi",
"Tadipatri Engg College, Tadipatri",
"Tammannagari Ramakrishna Reddy College of Engineering, Inole",
"Teegala Krishna Reddy Engineering College, Saroornagar",
"Tirumala Engineering College, Narasaraopet",
"TKR College of Engineering and Technology, Saroornagar",
"Universal College Of Engg And Technology, Guntur",
"University College of Engineering, Osmania University, Hyderabad",
"University of Hyderabad",
"Usha Rama College Of Engg And Technology, Telaprolu",
"Vaagdevi College of Engineering, Bollikunta",
"Vaagdevi Engineering College, Bollikunta",
"Vaagdevi Institute Of Technology. And Sci., Proddatur",
"Vardhaman College of Engineering, Kacharam",
"Vasavi College of Engineering, Hyderabad",
"Vasireddy Venkatadri Inst. Of Technology, Guntur",
"VBIT Ghatkesar, Ghatkesar",
"Velaga Nageswara Rao College Of Engineering, Ponnur",
"Vemu Institute Of Technology, Chittoor",
"Vidya Jyothi Institute of Science and Technology, Moinabad",
"Vignana Bharathi Institute of Technology, Ghatkesar",
"Vignana Bharathi Institute of technology, Korremulla",
"Vignan Institute of management and technology For Women, Ghatkesar",
"Vignans Inst Of Engineering For Women, Visakhapatnam",
"Vignan'S Institute Of Information Technology, Visakhapatnam",
"Vignan'S Nirula Inst Of Tech. And Sci For Women, Guntur",
"Vignans Lara Inst. Of Technology And Sci, Vadlamudi",
"Vijaya Inst. Of Technology For Women, Vijayawada",
"Vikas College Of Engineering And Technology, Vijayawada",
"Vikas Group Of Institutions, Vijayawada Rural",
"Visakha Inst Of Engg And Technology, Visakhapatnam",
"Visakha Technical Campus, Visakhapatnam",
"Vishnu Grp Of Instns - Vishnu Inst Of Technology, Bhimavaram",
"Visvodaya Engineering College, Kavali",
"Viswanadha Institute Of Technology And Mgmt, Visakhapatnam",
"Visvesvaraya College of Engineering and Technology, Ibrahmipatnam",
"VJIT Hyderabad, Hyderabad",
"Vkr Vnb And Agk Engineering College, Gudivada",
"VNR VJIET Hyderabad, Hyderabad",
"V R Siddhartha Engineering College, Vijayawada",
"Vrs And Yrn College Of Engg. And Technology, Chirala",
"V.S.Lakshmi Engg College For Women, Vijayawada",
"V.S.M College Of Engineering, Ramachandrapuram",
"Vizag Institute Of Technology, Bheemunipatnam",
"VNR Vignana Jyothi Institute of Engineering and Technology, Hyderabad",
"Wellfare Inst Of Science Tech And Mgmt, Pinagadi",
"West Godavari Instt Of Science And Engineering, Nallajerla",
"Ygvu Ysr Engineering College, Proddatur",
"Yogananda Inst Of Technology And Science, Tirupathi"